### ISSUE TITLE
Review comments for Movie-App 

### ISSUE THREAD

**Issue by Fawke** [HariPrasadMvsk/ES6-React-Training#5]
1. Separate this application into a git repo of its own.
2. Create a README.md file giving instructions to build and run the application.
3. Search funtionality not rendering movies properly.
![screenshot from 2018-07-18 19-02-42](https://user-images.githubusercontent.com/14229985/42884936-44820e80-8abd-11e8-9739-400637aec99e.png)
4. Unable to view and edit user collections. Incomplete Functionality.
5. Configure eslint in your repository and resolve all the lint errors.
6. Refactor your code to incorporate MVC structure, and adhere to Funtional Programming Paradigm. (This is your third Assignment)

**Comment by Fawke** [comment]
@HariPrasadMvsk, are you going to fix and close this issue?

**Comment by HariPrasadMvsk** [comment]
Hi Neelanjan,

Yes... I will do.  Give me some more time as I am tightly coupled with project deliverable's.  Surely I will fix if any help needed I will reach out to you.

Thanks,
Hari Prasad.

**Comment by Fawke** [comment]
Hi Hari, were you able to work on those issues?
